import re

file_path = "src/context/LanguageContext.tsx"
with open(file_path, "r") as f:
    content = f.read()

new_en_keys = """
    // Extra newly extracted keys
    'footer.marquee.bipoc': 'BIPOC Creative',
    'footer.marquee.ontario': 'Ontario',
    'footer.marquee.cultural': 'Cultural Storytelling',
    'footer.social.instagram': 'Instagram',
    'footer.social.linkedin': 'LinkedIn',
    'footer.social.email': 'Email',
    'footer.contact.review': 'Leave a Google Review',
    'nav.pricing.all.label': 'All Pricing',
    'nav.pricing.all.desc': 'View complete pricing guide',
    'nav.pricing.family': 'Family Portraits',
    'nav.pricing.family.desc': 'Mini Memories, Timeless Bonds, Legacy Heirloom',
    'nav.pricing.brand': 'Brand Identity',
    'nav.pricing.brand.desc': 'Profile Pro, Workspace Stories, Brand Vision',
    'nav.pricing.product': 'Product Photography',
    'nav.pricing.product.desc': 'E-commerce & lifestyle product shots',
    'nav.pricing.aerial': 'Aerial/Drone',
    'nav.pricing.aerial.desc': 'Cinematic aerial perspectives',
    'nav.pricing.events': 'Event Coverage',
    'nav.pricing.events.desc': 'Photo + video packages',
    'nav.pricing.social': 'Social Media',
    'nav.pricing.social.desc': 'Monthly management plans',
    'nav.pricing.design': 'Graphic Design',
    'nav.pricing.design.desc': 'Branding & visual identity',
    'nav.book.call': 'Book a Call',
    'nav.seen.label': 'SEEN — Upcoming Platform',
    'nav.book.call.mobile': 'Book a Discovery Call',
    'nav.pricing': 'Pricing',
    'nav.cart.aria': 'Shopping cart',
    'trust.test1.quote': "CREOVA's work on our Black History Month campaign was exceptional. They understood our vision and delivered beyond expectations.",
    'trust.test1.author': 'Human Rights & Equity',
    'trust.test1.org': 'Brock University',
    'trust.test2.quote': 'Professional, creative, and culturally aware. CREOVA brings authenticity to every project.',
    'trust.test2.author': 'BSSC Team',
    'trust.test2.org': 'Black Student Success Centre',
    'trust.test3.quote': 'Their photography captures the essence of our community. CREOVA is our go-to creative partner.',
    'trust.test3.author': 'BSA Leadership',
    'trust.test3.org': 'Black Students Association',
    'cart.cad': ' CAD',
    'common.loading': 'Loading...',
    
    // Contact Page Keys
    'contact.toast.captcha.expired': 'Security verification expired. Please verify again.',
    'contact.toast.captcha.issue': 'Security Verification Issue',
    'contact.toast.captcha.desc': 'Unable to verify. Please refresh and try again.',
    'contact.toast.captcha.missing': 'Please complete the CAPTCHA verification',
    'contact.badge.getintouch': 'Get In Touch',
    'contact.tag.book': 'Book Services',
    'contact.tag.collaborate': 'Collaborate',
    'contact.tag.inquiries': 'General Inquiries',
    'contact.book.title': 'Ready to book a session?',
    'contact.book.desc': "Skip the inquiry form and book directly — we'll confirm your session within 4 business hours.",
    'contact.book.btn.now': 'Book Session Now',
    'contact.book.btn.chat': 'Chat with Sankofa First',
    'contact.form.or': 'or send a general inquiry',
    'contact.form.title': 'Send Us a Message',
    'contact.form.label.name': 'Name *',
    'contact.form.placeholder.name': 'Your full name',
    'contact.form.label.email': 'Email *',
    'contact.form.placeholder.email': 'your@email.com',
    'contact.form.label.phone': 'Phone Number',
    'contact.form.placeholder.phone': '(123) 456-7890',
    'contact.form.label.service': 'Service Interested In *',
    'contact.form.select.service': 'Select a service',
    'contact.form.opt.family': 'Family Photography',
    'contact.form.opt.brand': 'Brand Photography',
    'contact.form.opt.product': 'Product Photography',
    'contact.form.opt.event': 'Event Coverage (Photo/Video)',
    'contact.form.opt.drone': 'Drone & Aerial Photography',
    'contact.form.opt.social': 'Social Media Management',
    'contact.form.opt.brandmgt': 'Brand Management',
    'contact.form.opt.collab': 'Collaboration Opportunity',
    'contact.form.opt.other': 'Other/Not Sure',
    'contact.form.label.budget': 'Budget Range',
    'contact.form.placeholder.budget': 'e.g., $500-$1000',
    'contact.form.label.timeline': 'Timeline/Event Date',
    'contact.form.placeholder.timeline': 'e.g., June 2026',
    'contact.form.label.message': 'Message *',
    'contact.form.placeholder.message': "Tell us about your project, event, or what you're looking for...",
    'contact.form.security': 'Security Verification',
    'contact.form.btn.sending': 'Sending...',
    'contact.form.btn.send': 'Send Message',
    'contact.form.disclaimer': 'By submitting this form, you agree to be contacted by CREOVA regarding your inquiry',
    'contact.faq.badge': 'Quick Answers',
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.q1': 'How far in advance should I book?',
    'contact.faq.a1': 'For events and weddings, we recommend booking 3-6 months in advance. For brand photography and other services, 2-4 weeks notice is typically sufficient, but we can sometimes accommodate rush requests.',
    'contact.faq.q2': 'Do you travel outside of Niagara?',
    'contact.faq.a2': 'Yes! We serve clients across Ontario and Canada-wide. Travel fees may apply for locations outside Niagara city limits and will be quoted based on distance.',
    'contact.faq.q3': "What's your cancellation policy?",
    'contact.faq.a3': 'We require a deposit to secure your booking. Cancellations made 14+ days before your session receive a 50% refund. Cancellations within 14 days forfeit the deposit. We can discuss rescheduling options for weather or emergencies.',
    'contact.faq.q4': 'How long until I receive my photos/videos?',
    'contact.faq.a4': 'Standard turnaround is 2-3 weeks for photography and 3-4 weeks for video projects. Expedited delivery (48-72 hours) is available for an additional fee.',
    'contact.faq.q5': 'Do you offer payment plans?',
    'contact.faq.a5': 'Yes, we offer payment plans for packages over $1,000. Typically, this includes a 50% deposit to book and the remaining balance due before or on the day of service.',
    'contact.faq.q6': 'What equipment do you use?',
    'contact.faq.a6': 'We use professional-grade Canon and Sony cameras, professional lighting equipment, DJI drones (licensed and insured), and industry-standard editing software including Adobe Creative Suite and Final Cut Pro.',
"""

new_fr_keys = """
    // Extra newly extracted keys
    'footer.marquee.bipoc': 'Créatifs BIPOC',
    'footer.marquee.ontario': 'Ontario',
    'footer.marquee.cultural': 'Narration Culturelle',
    'footer.social.instagram': 'Instagram',
    'footer.social.linkedin': 'LinkedIn',
    'footer.social.email': 'Courriel',
    'footer.contact.review': 'Laisser un Avis Google',
    'nav.pricing.all.label': 'Toute la Tarification',
    'nav.pricing.all.desc': 'Voir le guide des prix complet',
    'nav.pricing.family': 'Portraits de Famille',
    'nav.pricing.family.desc': 'Mini Souvenirs, Liens Intemporels, Héritage',
    'nav.pricing.brand': 'Identité de Marque',
    'nav.pricing.brand.desc': 'Profile Pro, Histoires d\\'Espace de Travail',
    'nav.pricing.product': 'Photographie de Produits',
    'nav.pricing.product.desc': 'Photos de produits e-commerce et style de vie',
    'nav.pricing.aerial': 'Aérien/Drone',
    'nav.pricing.aerial.desc': 'Perspectives aériennes cinématographiques',
    'nav.pricing.events': 'Couverture d\\'Événements',
    'nav.pricing.events.desc': 'Forfaits photo + vidéo',
    'nav.pricing.social': 'Médias Sociaux',
    'nav.pricing.social.desc': 'Forfaits de gestion mensuelle',
    'nav.pricing.design': 'Design Graphique',
    'nav.pricing.design.desc': 'Branding et identité visuelle',
    'nav.book.call': 'Réserver un Appel',
    'nav.seen.label': 'SEEN — Plateforme à Venir',
    'nav.book.call.mobile': 'Réserver un Appel Découverte',
    'nav.pricing': 'Tarification',
    'nav.cart.aria': 'Panier d\\'achat',
    'trust.test1.quote': "Le travail de CREOVA sur notre campagne du Mois de l'Histoire des Noirs a été exceptionnel. Ils ont compris notre vision et ont livré au-delà des attentes.",
    'trust.test1.author': 'Droits de la Personne & Équité',
    'trust.test1.org': 'Université Brock',
    'trust.test2.quote': 'Professionnel, créatif et conscient de la culture. CREOVA apporte de l\\'authenticité à chaque projet.',
    'trust.test2.author': 'Équipe BSSC',
    'trust.test2.org': 'Centre de Réussite des Étudiants Noirs',
    'trust.test3.quote': 'Leur photographie capture l\\'essence de notre communauté. CREOVA est notre partenaire créatif de choix.',
    'trust.test3.author': 'Leadership BSA',
    'trust.test3.org': 'Association des Étudiants Noirs',

    // Contact Page Keys
    'contact.toast.captcha.expired': 'La vérification de sécurité a expiré. Veuillez vérifier à nouveau.',
    'contact.toast.captcha.issue': 'Problème de Vérification de Sécurité',
    'contact.toast.captcha.desc': 'Impossible de vérifier. Veuillez rafraîchir et réessayer.',
    'contact.toast.captcha.missing': 'Veuillez compléter la vérification CAPTCHA',
    'contact.badge.getintouch': 'Contactez-nous',
    'contact.tag.book': 'Réserver des Services',
    'contact.tag.collaborate': 'Collaborer',
    'contact.tag.inquiries': 'Demandes Générales',
    'contact.book.title': 'Prêt à réserver une session ?',
    'contact.book.desc': "Passez le formulaire de demande et réservez directement — nous confirmerons votre session dans les 4 heures ouvrables.",
    'contact.book.btn.now': 'Réserver une Session Maintenant',
    'contact.book.btn.chat': 'Discuter avec Sankofa d\\'Abord',
    'contact.form.or': 'ou envoyez une demande générale',
    'contact.form.title': 'Envoyez-nous un Message',
    'contact.form.label.name': 'Nom *',
    'contact.form.placeholder.name': 'Votre nom complet',
    'contact.form.label.email': 'Email *',
    'contact.form.placeholder.email': 'votre@email.com',
    'contact.form.label.phone': 'Numéro de Téléphone',
    'contact.form.placeholder.phone': '(123) 456-7890',
    'contact.form.label.service': 'Service Souhaité *',
    'contact.form.select.service': 'Sélectionner un service',
    'contact.form.opt.family': 'Photographie de Famille',
    'contact.form.opt.brand': 'Photographie de Marque',
    'contact.form.opt.product': 'Photographie de Produit',
    'contact.form.opt.event': 'Couverture d\\'Événements (Photo/Vidéo)',
    'contact.form.opt.drone': 'Photographie par Drone & Aérienne',
    'contact.form.opt.social': 'Gestion des Médias Sociaux',
    'contact.form.opt.brandmgt': 'Gestion de Marque',
    'contact.form.opt.collab': 'Opportunité de Collaboration',
    'contact.form.opt.other': 'Autre/Pas Sûr',
    'contact.form.label.budget': 'Fourchette de Budget',
    'contact.form.placeholder.budget': 'ex. 500$-1000$',
    'contact.form.label.timeline': 'Calendrier/Date de l\\'Événement',
    'contact.form.placeholder.timeline': 'ex. Juin 2026',
    'contact.form.label.message': 'Message *',
    'contact.form.placeholder.message': "Parlez-nous de votre projet, événement, ou de ce que vous recherchez...",
    'contact.form.security': 'Vérification de Sécurité',
    'contact.form.btn.sending': 'Envoi en cours...',
    'contact.form.btn.send': 'Envoyer le Message',
    'contact.form.disclaimer': 'En soumettant ce formulaire, vous acceptez d\\'être contacté par CREOVA concernant votre demande',
    'contact.faq.badge': 'Réponses Rapides',
    'contact.faq.title': 'Foire Aux Questions',
    'contact.faq.q1': 'Combien de temps à l\\'avance dois-je réserver ?',
    'contact.faq.a1': 'Pour les événements et mariages, nous recommandons de réserver 3-6 mois à l\\'avance. Pour la photographie de marque et autres services, un préavis de 2-4 semaines est généralement suffisant, mais nous pouvons parfois accommoder des demandes urgentes.',
    'contact.faq.q2': 'Vous déplacez-vous en dehors de Niagara ?',
    'contact.faq.a2': 'Oui ! Nous servons des clients partout en Ontario et au Canada. Des frais de déplacement peuvent s\\'appliquer pour les lieux en dehors des limites de Niagara et seront indiqués en fonction de la distance.',
    'contact.faq.q3': "Quelle est votre politique d'annulation ?",
    'contact.faq.a3': 'Nous demandons un dépôt pour garantir votre réservation. Les annulations effectuées plus de 14 jours avant votre session recevront un remboursement de 50 %. Les annulations dans les 14 jours entraînent la perte du dépôt. Nous pouvons discuter des options de report en cas de météo ou d\\'urgence.',
    'contact.faq.q4': 'Combien de temps avant de recevoir mes photos/vidéos ?',
    'contact.faq.a4': 'Le délai standard est de 2-3 semaines pour la photographie et de 3-4 semaines pour les projets vidéo. Une livraison accélérée (48-72 heures) est disponible moyennant des frais supplémentaires.',
    'contact.faq.q5': 'Proposez-vous des plans de paiement ?',
    'contact.faq.a5': 'Oui, nous proposons des plans de paiement pour les forfaits de plus de 1 000 $. En général, cela inclut un dépôt de 50 % à la réservation et le solde dû avant ou le jour du service.',
    'contact.faq.q6': 'Quel équipement utilisez-vous ?',
    'contact.faq.a6': 'Nous utilisons des appareils photo de qualité professionnelle Canon et Sony, de l\\'équipement d\\'éclairage professionnel, des drones DJI (sous licence et assurés) et des logiciels de montage de référence comme Adobe Creative Suite et Final Cut Pro.',
"""

# Find en: { and insert after it
en_match = re.search(r'en:\s*\{', content)
if en_match:
    pos = en_match.end()
    content = content[:pos] + "\\n" + new_en_keys + content[pos:]

# Find fr: { and insert after it
fr_match = re.search(r'fr:\s*\{', content)
if fr_match:
    pos = fr_match.end()
    content = content[:pos] + "\\n" + new_fr_keys + content[pos:]

with open(file_path, "w") as f:
    f.write(content)

print("LanguageContext.tsx patched perfectly.")
