const fs = require('fs');
const path = require('path');

const contextPath = path.join(__dirname, 'src/context/LanguageContext.tsx');
let content = fs.readFileSync(contextPath, 'utf-8');

const newEnKeys = `
    // Contact Page Keys
    'contact.toast.captcha.expired': 'Security verification expired. Please verify again.',
    'contact.toast.captcha.issue': 'Security Verification Issue',
    'contact.toast.captcha.desc': 'Unable to verify. Please refresh and try again.',
    'contact.toast.captcha.missing': 'Please complete the CAPTCHA verification',
    'contact.badge.getintouch': 'Get In Touch',
    'contact.tag.book': 'Book Services',
    'contact.tag.collaborate': 'Collaborate',
    'contact.tag.inquiries': 'General Inquiries',
    'contact.book.title': 'Ready to book a session?',
    'contact.book.desc': "Skip the inquiry form and book directly — we'll confirm your session within 4 business hours.",
    'contact.book.btn.now': 'Book Session Now',
    'contact.book.btn.chat': 'Chat with Sankofa First',
    'contact.form.or': 'or send a general inquiry',
    'contact.form.title': 'Send Us a Message',
    'contact.form.label.name': 'Name *',
    'contact.form.placeholder.name': 'Your full name',
    'contact.form.label.email': 'Email *',
    'contact.form.placeholder.email': 'your@email.com',
    'contact.form.label.phone': 'Phone Number',
    'contact.form.placeholder.phone': '(123) 456-7890',
    'contact.form.label.service': 'Service Interested In *',
    'contact.form.select.service': 'Select a service',
    'contact.form.opt.family': 'Family Photography',
    'contact.form.opt.brand': 'Brand Photography',
    'contact.form.opt.product': 'Product Photography',
    'contact.form.opt.event': 'Event Coverage (Photo/Video)',
    'contact.form.opt.drone': 'Drone & Aerial Photography',
    'contact.form.opt.social': 'Social Media Management',
    'contact.form.opt.brandmgt': 'Brand Management',
    'contact.form.opt.collab': 'Collaboration Opportunity',
    'contact.form.opt.other': 'Other/Not Sure',
    'contact.form.label.budget': 'Budget Range',
    'contact.form.placeholder.budget': 'e.g., $500-$1000',
    'contact.form.label.timeline': 'Timeline/Event Date',
    'contact.form.placeholder.timeline': 'e.g., June 2026',
    'contact.form.label.message': 'Message *',
    'contact.form.placeholder.message': "Tell us about your project, event, or what you're looking for...",
    'contact.form.security': 'Security Verification',
    'contact.form.btn.sending': 'Sending...',
    'contact.form.btn.send': 'Send Message',
    'contact.form.disclaimer': 'By submitting this form, you agree to be contacted by CREOVA regarding your inquiry',
    'contact.faq.badge': 'Quick Answers',
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.q1': 'How far in advance should I book?',
    'contact.faq.a1': 'For events and weddings, we recommend booking 3-6 months in advance. For brand photography and other services, 2-4 weeks notice is typically sufficient, but we can sometimes accommodate rush requests.',
    'contact.faq.q2': 'Do you travel outside of Niagara?',
    'contact.faq.a2': 'Yes! We serve clients across Ontario and Canada-wide. Travel fees may apply for locations outside Niagara city limits and will be quoted based on distance.',
    'contact.faq.q3': "What's your cancellation policy?",
    'contact.faq.a3': 'We require a deposit to secure your booking. Cancellations made 14+ days before your session receive a 50% refund. Cancellations within 14 days forfeit the deposit. We can discuss rescheduling options for weather or emergencies.',
    'contact.faq.q4': 'How long until I receive my photos/videos?',
    'contact.faq.a4': 'Standard turnaround is 2-3 weeks for photography and 3-4 weeks for video projects. Expedited delivery (48-72 hours) is available for an additional fee.',
    'contact.faq.q5': 'Do you offer payment plans?',
    'contact.faq.a5': 'Yes, we offer payment plans for packages over $1,000. Typically, this includes a 50% deposit to book and the remaining balance due before or on the day of service.',
    'contact.faq.q6': 'What equipment do you use?',
    'contact.faq.a6': 'We use professional-grade Canon and Sony cameras, professional lighting equipment, DJI drones (licensed and insured), and industry-standard editing software including Adobe Creative Suite and Final Cut Pro.',
`;

const newFrKeys = `
    // Contact Page Keys
    'contact.toast.captcha.expired': 'La vérification de sécurité a expiré. Veuillez vérifier à nouveau.',
    'contact.toast.captcha.issue': 'Problème de Vérification de Sécurité',
    'contact.toast.captcha.desc': 'Impossible de vérifier. Veuillez rafraîchir et réessayer.',
    'contact.toast.captcha.missing': 'Veuillez compléter la vérification CAPTCHA',
    'contact.badge.getintouch': 'Contactez-nous',
    'contact.tag.book': 'Réserver des Services',
    'contact.tag.collaborate': 'Collaborer',
    'contact.tag.inquiries': 'Demandes Générales',
    'contact.book.title': 'Prêt à réserver une session ?',
    'contact.book.desc': "Passez le formulaire de demande et réservez directement — nous confirmerons votre session dans les 4 heures ouvrables.",
    'contact.book.btn.now': 'Réserver une Session Maintenant',
    'contact.book.btn.chat': 'Discuter avec Sankofa d\\'Abord',
    'contact.form.or': 'ou envoyez une demande générale',
    'contact.form.title': 'Envoyez-nous un Message',
    'contact.form.label.name': 'Nom *',
    'contact.form.placeholder.name': 'Votre nom complet',
    'contact.form.label.email': 'Email *',
    'contact.form.placeholder.email': 'votre@email.com',
    'contact.form.label.phone': 'Numéro de Téléphone',
    'contact.form.placeholder.phone': '(123) 456-7890',
    'contact.form.label.service': 'Service Souhaité *',
    'contact.form.select.service': 'Sélectionner un service',
    'contact.form.opt.family': 'Photographie de Famille',
    'contact.form.opt.brand': 'Photographie de Marque',
    'contact.form.opt.product': 'Photographie de Produit',
    'contact.form.opt.event': 'Couverture d\\'Événements (Photo/Vidéo)',
    'contact.form.opt.drone': 'Photographie par Drone & Aérienne',
    'contact.form.opt.social': 'Gestion des Médias Sociaux',
    'contact.form.opt.brandmgt': 'Gestion de Marque',
    'contact.form.opt.collab': 'Opportunité de Collaboration',
    'contact.form.opt.other': 'Autre/Pas Sûr',
    'contact.form.label.budget': 'Fourchette de Budget',
    'contact.form.placeholder.budget': 'ex. 500$-1000$',
    'contact.form.label.timeline': 'Calendrier/Date de l\\'Événement',
    'contact.form.placeholder.timeline': 'ex. Juin 2026',
    'contact.form.label.message': 'Message *',
    'contact.form.placeholder.message': "Parlez-nous de votre projet, événement, ou de ce que vous recherchez...",
    'contact.form.security': 'Vérification de Sécurité',
    'contact.form.btn.sending': 'Envoi en cours...',
    'contact.form.btn.send': 'Envoyer le Message',
    'contact.form.disclaimer': 'En soumettant ce formulaire, vous acceptez d\\'être contacté par CREOVA concernant votre demande',
    'contact.faq.badge': 'Réponses Rapides',
    'contact.faq.title': 'Foire Aux Questions',
    'contact.faq.q1': 'Combien de temps à l\\'avance dois-je réserver ?',
    'contact.faq.a1': 'Pour les événements et mariages, nous recommandons de réserver 3-6 mois à l\\'avance. Pour la photographie de marque et autres services, un préavis de 2-4 semaines est généralement suffisant, mais nous pouvons parfois accommoder des demandes urgentes.',
    'contact.faq.q2': 'Vous déplacez-vous en dehors de Niagara ?',
    'contact.faq.a2': 'Oui ! Nous servons des clients partout en Ontario et au Canada. Des frais de déplacement peuvent s\\'appliquer pour les lieux en dehors des limites de Niagara et seront indiqués en fonction de la distance.',
    'contact.faq.q3': "Quelle est votre politique d'annulation ?",
    'contact.faq.a3': 'Nous demandons un dépôt pour garantir votre réservation. Les annulations effectuées plus de 14 jours avant votre session recevront un remboursement de 50 %. Les annulations dans les 14 jours entraînent la perte du dépôt. Nous pouvons discuter des options de report en cas de météo ou d\\'urgence.',
    'contact.faq.q4': 'Combien de temps avant de recevoir mes photos/vidéos ?',
    'contact.faq.a4': 'Le délai standard est de 2-3 semaines pour la photographie et de 3-4 semaines pour les projets vidéo. Une livraison accélérée (48-72 heures) est disponible moyennant des frais supplémentaires.',
    'contact.faq.q5': 'Proposez-vous des plans de paiement ?',
    'contact.faq.a5': 'Oui, nous proposons des plans de paiement pour les forfaits de plus de 1 000 $. En général, cela inclut un dépôt de 50 % à la réservation et le solde dû avant ou le jour du service.',
    'contact.faq.q6': 'Quel équipement utilisez-vous ?',
    'contact.faq.a6': 'Nous utilisons des appareils photo de qualité professionnelle Canon et Sony, de l\\'équipement d\\'éclairage professionnel, des drones DJI (sous licence et assurés) et des logiciels de montage de référence comme Adobe Creative Suite et Final Cut Pro.',
`;

content = content.replace(/(en:\s*\{)/, "$1\\n" + newEnKeys);
content = content.replace(/(fr:\s*\{)/, "$1\\n" + newFrKeys);

fs.writeFileSync(contextPath, content);
console.log('LanguageContext.tsx patched successfully for Contact Page.');
